#!/usr/bin/env python3
"""
12-Signal Breadth Probe & Offline Gating Analysis
=================================================
Scans feature dump files generated by `--dump_features` in unsup_kitti-c.py and evaluates:
1. Complementarity AUROC (Test D1 generalized) on the epistemic-rejected subset.
2. Harvestable Yield at the target epistemic precision bar (~98.8%).
3. Pairwise Pearson Correlation Matrix across all 12 candidate signals.
4. 2D Decision Boundary Fitting (Cascade vs Ellipsoid vs Soft-Weight Ramp) for dual gating.

Usage:
    python analyze_12signal_dump.py --log_dir logs/d5_d6_features_dump
"""

import os
import glob
import argparse
import numpy as np
import torch
from sklearn.metrics import roc_auc_score

def load_dump_files(log_dir):
    pattern = os.path.join(log_dir, "features_dump_*.pt")
    files = glob.glob(pattern)
    if not files:
        # Also check subdirectories
        pattern = os.path.join(log_dir, "**", "features_dump_*.pt")
        files = glob.glob(pattern, recursive=True)
        
    if not files:
        raise FileNotFoundError(f"No feature dump files found matching {pattern}")
        
    print(f"Found {len(files)} dump files in {log_dir}. Loading...")
    all_dicts = []
    for fpath in sorted(files):
        try:
            data = torch.load(fpath, map_location='cpu')
            if isinstance(data, list):
                all_dicts.extend(data)
            elif isinstance(data, dict):
                all_dicts.append(data)
        except Exception as e:
            print(f"Warning: could not load {fpath}: {e}")
            
    if not all_dicts:
        raise ValueError("Loaded files contained no data.")
        
    # Ensure we only process frames that contain all expected keys and matching lengths
    required_keys = [
        'gt_corr', 'epi_score', 'msp', 'margin', 'entropy', 'energy', 'dirichlet_mi',
        'z_score', 'rel_mahal', 'knn_dist', 'latent_norm', 'view_dis', 'soft_view_var',
        'range', 'intensity'
    ]
    
    valid_dicts = []
    for d in all_dicts:
        if all(k in d and d[k] is not None for k in required_keys):
            n_pts = len(d['gt_corr'])
            if all(len(d[k]) == n_pts for k in required_keys):
                valid_dicts.append(d)
                
    if not valid_dicts:
        fallback_keys = [k for k in all_dicts[0].keys() if all_dicts[0][k] is not None]
        print(f"Warning: No frame contained all 15 required 12-signal keys. Falling back to {len(fallback_keys)} keys from first frame.")
        for d in all_dicts:
            if all(k in d and d[k] is not None for k in fallback_keys):
                n_pts = len(d['gt_corr'])
                if all(len(d[k]) == n_pts for k in fallback_keys):
                    valid_dicts.append(d)
        required_keys = fallback_keys
        
    if len(valid_dicts) < len(all_dicts):
        print(f"Filtered out {len(all_dicts) - len(valid_dicts)} incompatible/older frames. Using {len(valid_dicts)} complete frames.")
        
    merged = {}
    for k in required_keys:
        tensors = [d[k] for d in valid_dicts]
        merged[k] = torch.cat(tensors, dim=0).numpy()
        
    print(f"Loaded total of {len(merged['gt_corr']):,} points across {len(valid_dicts)} frames.")
    return merged

def prepare_signals(data):
    """
    Standardizes signal directions so that HIGHER = MORE CONFIDENT / ADMIT.
    Returns dictionary of named signals and their family tags.
    """
    signals = {}
    
    # Family N: Evidential / Probabilistic
    if 'epi_score' in data:
        signals['N1_epi_score'] = data['epi_score']  # -uncertainty (higher = better)
    if 'msp' in data:
        signals['N2_msp'] = data['msp']              # max softmax prob (higher = better)
    if 'margin' in data:
        signals['N3_margin'] = data['margin']        # top1 - top2 logit (higher = better)
    if 'entropy' in data:
        signals['N4_neg_entropy'] = -data['entropy'] # lower entropy = better
    if 'energy' in data:
        signals['N5_pos_energy'] = data['energy']    # logsumexp (higher = better)
    if 'dirichlet_mi' in data:
        signals['N6_neg_mi'] = -data['dirichlet_mi'] # lower MI = better
        
    # Family G: Geometric / HDC
    if 'z_score' in data:
        signals['G1_z_score'] = data['z_score']      # standardized cos sim (higher = better)
    if 'rel_mahal' in data:
        signals['G2_neg_rel_mahal'] = -data['rel_mahal'] # closer to own class = better
    if 'knn_dist' in data:
        signals['G3_neg_knn_dist'] = -data['knn_dist']   # closer to bank = better
    if 'latent_norm' in data:
        signals['G5_latent_norm'] = data['latent_norm']  # L2 norm
        
    # Family V: Perturbation / Cross-View
    if 'view_dis' in data:
        signals['V1_neg_view_dis'] = -data['view_dis']   # 0=agree (0), 1=disagree (-1) -> higher=better
    if 'soft_view_var' in data:
        signals['V2_neg_view_var'] = -data['soft_view_var'] # lower variance = better
        
    # Family I: Input / Raw Sensor
    if 'range' in data:
        signals['I1_neg_range'] = -data['range']         # closer points usually cleaner
    if 'intensity' in data:
        signals['I2_intensity'] = data['intensity']
        
    return signals

def analyze_complementarity_and_yield(data, signals, admitted_mask):
    gt_corr = data['gt_corr'].astype(bool)
    rejected_mask = ~admitted_mask
    
    n_total = len(gt_corr)
    n_admitted = admitted_mask.sum()
    n_rejected = rejected_mask.sum()
    
    if n_admitted == 0 or n_rejected == 0:
        print("Error: All points are either admitted or rejected after thresholding.")
        return
        
    p_epi_admitted = gt_corr[admitted_mask].mean()
    p_epi_rejected = gt_corr[rejected_mask].mean()
    
    print("\n" + "="*70)
    print("BASELINE EPISTEMIC GATING PERFORMANCE")
    print("="*70)
    print(f"Total Points:        {n_total:,}")
    print(f"Epistemic Admitted:  {n_admitted:,} ({n_admitted/n_total*100:.1f}%) | GT Precision: {p_epi_admitted*100:.2f}%")
    print(f"Epistemic Rejected:  {n_rejected:,} ({n_rejected/n_total*100:.1f}%) | GT Precision: {p_epi_rejected*100:.2f}%")
    print("="*70)
    
    # We evaluate AUROC on the Rejected subset (Test D1 Generalized)
    print("\n" + "-"*70)
    print(f"1. COMPLEMENTARITY AUROC & HARVESTABLE YIELD (Target Precision >= {p_epi_admitted*100:.2f}%)")
    print("-"*70)
    print(f"{'Signal Name':<20} | {'Family':<6} | {'Rej AUROC':<10} | {'Rescued Pt':<12} | {'Volume +%':<10} | {'Final Prec':<10}")
    print("-"*70)
    
    results = {}
    gt_rej = gt_corr[rejected_mask]
    
    # Pre-count correct and total in baseline admitted
    base_correct = gt_corr[admitted_mask].sum()
    base_total = n_admitted
    
    for sig_name, sig_vals in sorted(signals.items()):
        family = sig_name[:2]
        sig_rej = sig_vals[rejected_mask]
        
        # AUROC on rejected subset
        try:
            if len(np.unique(gt_rej)) > 1 and np.std(sig_rej) > 1e-9:
                auroc = roc_auc_score(gt_rej, sig_rej)
            else:
                auroc = 0.500
        except Exception:
            auroc = 0.500
            
        # Harvestable Yield: rank rejected points descending by signal
        sort_idx = np.argsort(sig_rej)[::-1]
        sorted_gt_rej = gt_rej[sort_idx]
        
        cum_correct_rej = np.cumsum(sorted_gt_rej)
        cum_total_rej = np.arange(1, len(sorted_gt_rej) + 1)
        
        combined_prec = (base_correct + cum_correct_rej) / (base_total + cum_total_rej)
        
        # Find largest k where combined_prec >= p_epi_admitted
        valid_k = np.where(combined_prec >= p_epi_admitted)[0]
        if len(valid_k) > 0:
            best_k = valid_k[-1] + 1
            rescued_pts = best_k
            vol_increase = (rescued_pts / base_total) * 100.0
            final_p = combined_prec[best_k - 1] * 100.0
        else:
            rescued_pts = 0
            vol_increase = 0.0
            final_p = p_epi_admitted * 100.0
            
        results[sig_name] = (auroc, rescued_pts, vol_increase, final_p)
        print(f"{sig_name:<20} | {family:<6} | {auroc:10.4f} | {rescued_pts:<12,d} | {vol_increase:9.2f}% | {final_p:9.2f}%")
        
    print("-"*70)
    return results

def print_correlation_matrix(signals):
    print("\n" + "="*70)
    print("2. PAIRWISE PEARSON CORRELATION MATRIX (Across All Evaluated Points)")
    print("="*70)
    
    names = sorted(signals.keys())
    short_names = [n.split('_', 1)[0] for n in names]
    
    # Build matrix
    mat = np.zeros((len(names), len(names)))
    for i, n1 in enumerate(names):
        for j, n2 in enumerate(names):
            v1 = signals[n1]
            v2 = signals[n2]
            if np.std(v1) > 1e-9 and np.std(v2) > 1e-9:
                mat[i, j] = np.corrcoef(v1, v2)[0, 1]
            else:
                mat[i, j] = 0.0
                
    # Print header
    header = "      " + "".join([f"{sn:>8}" for sn in short_names])
    print(header)
    for i, sn in enumerate(short_names):
        row_str = f"{sn:<5} " + "".join([f"{mat[i,j]:8.2f}" for j in range(len(names))])
        print(row_str)
    print("="*70)

def fit_2d_decision_boundaries(data, signals, base_admitted):
    """
    Fits 2D decision boundaries on (N1_epi_score, G1_z_score) or best orthogonal pair.
    Compares 3 architectures:
    1. Cascade / OR-Rescue: Admit if epi >= 0 OR (epi < 0 AND geom >= th_geom)
    2. Linear Ramp / Soft Weighting: Admit if w1*epi + w2*geom >= th
    3. Ellipsoid / Quadratic: Admit if (epi - mu1)^2 / a^2 + (geom - mu2)^2 / b^2 <= 1 (when above center)
    """
    if 'N1_epi_score' not in signals or 'G1_z_score' not in signals:
        return
        
    print("\n" + "="*70)
    print("3. 2D DECISION BOUNDARY PROBE (N1_epi_score x G1_z_score)")
    print("="*70)
    
    gt_corr = data['gt_corr'].astype(bool)
    x = signals['N1_epi_score'] # epi_score
    y = signals['G1_z_score']   # z_score
    
    if base_admitted.sum() == 0 or (~base_admitted).sum() == 0:
        print("Skipping 2D boundary fitting due to empty admitted or rejected set.")
        return
        
    base_correct = gt_corr[base_admitted].sum()
    base_total = base_admitted.sum()
    p_target = gt_corr[base_admitted].mean()
    
    rej_mask = ~base_admitted
    gt_rej = gt_corr[rej_mask]
    y_rej = y[rej_mask]
    x_rej = x[rej_mask]
    
    # 1. Cascade / OR-Rescue: Find threshold on y_rej that maximizes rescued points while prec >= p_target
    sort_idx = np.argsort(y_rej)[::-1]
    sorted_gt = gt_rej[sort_idx]
    cum_corr = np.cumsum(sorted_gt)
    cum_tot = np.arange(1, len(sorted_gt) + 1)
    comb_prec = (base_correct + cum_corr) / (base_total + cum_tot)
    
    valid_k = np.where(comb_prec >= p_target)[0]
    if len(valid_k) > 0:
        best_k_casc = valid_k[-1] + 1
        th_geom = y_rej[sort_idx][best_k_casc - 1]
        yield_casc = best_k_casc
        prec_casc = comb_prec[best_k_casc - 1] * 100.0
    else:
        yield_casc, th_geom, prec_casc = 0, float('nan'), p_target * 100.0
        
    # 2. Linear Ramp / Soft Weighting: w * x_rej + (1-w) * y_rej
    best_yield_linear = 0
    best_w = 0.5
    best_prec_linear = p_target * 100.0
    
    # Normalize x and y on rejected subset to roughly similar scales for grid search
    x_std = np.std(x_rej) if np.std(x_rej) > 1e-9 else 1.0
    y_std = np.std(y_rej) if np.std(y_rej) > 1e-9 else 1.0
    
    for w in np.linspace(0.0, 1.0, 21):
        score_lin = w * (x_rej / x_std) + (1.0 - w) * (y_rej / y_std)
        s_idx = np.argsort(score_lin)[::-1]
        s_gt = gt_rej[s_idx]
        c_corr = np.cumsum(s_gt)
        c_tot = np.arange(1, len(s_gt) + 1)
        c_prec = (base_correct + c_corr) / (base_total + c_tot)
        vk = np.where(c_prec >= p_target)[0]
        if len(vk) > 0 and (vk[-1] + 1) > best_yield_linear:
            best_yield_linear = vk[-1] + 1
            best_w = w
            best_prec_linear = c_prec[vk[-1]] * 100.0
            
    # 3. Ellipsoid / Quadratic Gate (on entire space)
    # Admit if point is in baseline OR inside an ellipse in the upper-left quadrant (high geom, slightly neg epi)
    best_yield_ellip = 0
    best_prec_ellip = p_target * 100.0
    
    for alpha in np.linspace(0.5, 3.0, 15):
        # Quadratic score on rejected: penalize negative epi quadratically, reward positive geom linearly/quadratically
        score_quad = (y_rej / y_std) - alpha * ((x_rej / x_std) ** 2)
        s_idx = np.argsort(score_quad)[::-1]
        s_gt = gt_rej[s_idx]
        c_corr = np.cumsum(s_gt)
        c_tot = np.arange(1, len(s_gt) + 1)
        c_prec = (base_correct + c_corr) / (base_total + c_tot)
        vk = np.where(c_prec >= p_target)[0]
        if len(vk) > 0 and (vk[-1] + 1) > best_yield_ellip:
            best_yield_ellip = vk[-1] + 1
            best_prec_ellip = c_prec[vk[-1]] * 100.0

    print(f"{'Architecture Model':<25} | {'Rescued Points':<15} | {'Volume Increase':<15} | {'Final Precision':<15}")
    print("-"*75)
    print(f"{'1. Cascade / OR-Rescue':<25} | {yield_casc:<15,d} | {(yield_casc/base_total)*100:13.2f}% | {prec_casc:13.2f}%")
    print(f"{'2. Linear Ramp (Soft W)':<25} | {best_yield_linear:<15,d} | {(best_yield_linear/base_total)*100:13.2f}% | {best_prec_linear:13.2f}%")
    print(f"{'3. Ellipsoid (Quadratic)':<25} | {best_yield_ellip:<15,d} | {(best_yield_ellip/base_total)*100:13.2f}% | {best_prec_ellip:13.2f}%")
    print("="*75)
    print("Conclusion: Check which boundary shape yields the highest rescued point volume without precision loss.")

def main():
    parser = argparse.ArgumentParser(description="12-Signal Breadth Probe & Offline Analysis")
    parser.add_argument("--log_dir", type=str, default="logs/d5_d6_features_dump", help="Directory containing features_dump_*.pt files")
    args = parser.parse_args()
    
    try:
        data = load_dump_files(args.log_dir)
    except Exception as e:
        print(f"Error loading dump files: {e}")
        return
        
    signals = prepare_signals(data)
    
    # In unsup_kitti-c.py, epistemic_decay = exp(-2.0 * relu(uncertainty - 0.5)).
    # Points are admitted when epistemic_decay >= 0.5.
    u_vals = -signals.get('N1_epi_score', -data.get('epi_score', np.zeros(len(data['gt_corr']))))
    epi_decay = np.exp(-2.0 * np.maximum(0.0, u_vals - 0.5))
    admitted_mask = epi_decay >= 0.5
    
    if admitted_mask.sum() == 0 or (~admitted_mask).sum() == 0:
        med_val = np.median(epi_decay)
        print(f"Warning: Standard threshold (epi_decay >= 0.5) resulted in admitted={admitted_mask.sum():,}, rejected={(~admitted_mask).sum():,}. Using median split (>= {med_val:.4f}).")
        admitted_mask = epi_decay >= med_val
        
    analyze_complementarity_and_yield(data, signals, admitted_mask)
    print_correlation_matrix(signals)
    fit_2d_decision_boundaries(data, signals, admitted_mask)

if __name__ == "__main__":
    main()
